### ISSUE TITLE
Marks on Symbols

### ISSUE THREAD

**Issue by kalapi** [mekkablue/ShowMarkPreview#11]
Preview does not work with uni25CC or `dottedCircle` since the category `Symbol` isn't included in the code. Example:

<img width="664" alt="Screen Shot 2019-03-11 at 11 43 20 AM" src="https://user-images.githubusercontent.com/15804460/54121641-e97de780-43f2-11e9-971b-2019b68f6397.png">

**Comment by mekkablue** [comment]
Shall we make just `dottedCircle` an exception? Is there any other symbol that needs mark attachment?

**Comment by kalapi** [comment]
Exception as in:
a. include only `dottedCircle` and ignore all other symbols
b. not do anything

**Comment by mekkablue** [comment]
Like ‘a’, only add dottedCircle. I will do that for now.
