### ISSUE TITLE
Preview not working when anchor name begins with #

### ISSUE THREAD

**Issue by kalapi** [mekkablue/ShowMarkPreview#12]
I have anchor names starting with `#` in order to prevent them from exporting to GPOS. In this instance, mark preview does not work. Example:

With `#` anchor name
<img width="368" alt="Screen Shot 2019-03-11 at 11 45 10 AM" src="https://user-images.githubusercontent.com/15804460/54121963-b0924280-43f3-11e9-98c4-0f1c9b70a78f.png">

Without `#` anchor name
<img width="350" alt="Screen Shot 2019-03-11 at 11 45 20 AM" src="https://user-images.githubusercontent.com/15804460/54121986-c273e580-43f3-11e9-8b04-3da6a3e7c10b.png">

**Comment by mekkablue** [comment]
What should it preview when you cannot use them as marks?
Wouldn't it be misleading if the plug-in were to show mark combining that is not in the font?

**Comment by kalapi** [comment]
I was not clear in my explanation. I meant to say that when a mark glyph includes '#' name anchor, mark preview for all other anchors switches off.

The _anusvara_ (dot mark above) has two '_' anchors (`_top` and `_#topRight`). The base-glyph _Ma_ only contains `top`. The following images show two states—in the left image the _anusvara_ has a '#' anchor, while in the right I deleted the '#' anchor to illustrate that the mark preview works with the `_top/top` anchors. 

<img width="150" alt="Screen Shot 2019-03-29 at 5 30 57 PM" src="https://user-images.githubusercontent.com/15804460/55231465-ab812000-5248-11e9-82ee-666fa64d4c26.png"><img width="148" alt="Screen Shot 2019-03-29 at 5 31 12 PM" src="https://user-images.githubusercontent.com/15804460/55231471-ade37a00-5248-11e9-9d8f-424188829435.png">

**Comment by mekkablue** [comment]
Thank, now I get it. :) I had a look and it always only takes the first underscored anchor (alphabetically) into account. I’ll try and exclude mark/mkmk disabled anchors. (A little tricky because it is not only # but any non-letter.)
