### ISSUE TITLE
Plugin not accessible anymore in v2.6.5 (1342)

### ISSUE THREAD

**Issue by kalapi** [mekkablue/ShowMarkPreview#13]
Hello! 

This is a strange issue. I've not updated any related libs/apps. Just randomly stopped working. I've tried manually re-installing as well as installing from the plugin manager.

Any ideas? Thanks in advance!

**Comment by schriftgestalt** [comment]
can you try in the latest cutting edge version (from yesterday)?

**Comment by kalapi** [comment]
Nope, no change. I've updated to Version 2.6.7 (1355).

All the other plugins are working fine.

**Comment by schriftgestalt** [comment]
I fixe it in 136e573
