### ISSUE TITLE
Bases made of components

### ISSUE THREAD

**Issue by ohbendy** [mekkablue/ShowMarkPreview#2]
Hello again, I've noticed that when a base is made of components (and anchors are not explicitly defined but inherited from the components), the marks do not show on that base.

**Comment by mekkablue** [comment]
Ah, yes, you are right of course, looking into it.

**Comment by mekkablue** [comment]
I think I fixed it. Please try the latest version.

**Comment by ohbendy** [comment]
Yes it works! Thanks :-)

Not sure what the behaviour should be on ligatures with top_1 and top_2 anchors...
