### ISSUE TITLE
Conflict with TrueType tool

### ISSUE THREAD

**Issue by jenskutilek** [mekkablue/ShowMarkPreview#3]
When I have ShowMarkPreview installed, the TrueType point alignment can't be set properly. See https://forum.glyphsapp.com/t/truetype-hint-alignment-1097/7806

This affects at least Glyphs 1097–1099 in my experience. I have no idea where to start looking as there are no messages in the console or macro panel output.

**Comment by mekkablue** [comment]
The latest update should fix this. Thx @schriftgestalt for pull.
