### ISSUE TITLE
Preview and text mode

### ISSUE THREAD

**Issue by ohbendy** [mekkablue/ShowMarkPreview#5]
It would be handy if the marks would go black with the other glyphs when pressing spacebar or when in text mode, I think.

**Comment by mekkablue** [comment]
On my list, but a little tricky in Python, I think.

**Comment by Mark2Mark** [comment]
> On my list, but a little tricky in Python, I think.

I don’t think so, maybe I’m wrong, but I got all the needed snippets scattered in some plugins. I can try next week to make that happen.

Johannes N. added [this to Smart Plumblines](https://github.com/Mark2Mark/Show-Smart-Plumblines/commit/6c0d1f3879bd7a377cea0ff44f042268b9c01276) … I think that’s almost all we need basically, if I’m not mistaken.
